# Generated by Django 5.1.4 on 2025-05-26 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingapp', '0004_order_address_order_city_order_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('style', models.CharField(choices=[('oil', 'Oil Painting'), ('watercolor', 'Watercolor'), ('sketch', 'Sketch'), ('popart', 'Pop Art'), ('impressionist', 'Impressionist')], max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small (12" x 16")'), ('medium', 'Medium (16" x 20")'), ('large', 'Large (20" x 24")'), ('xlarge', 'Extra Large (24" x 36")')], max_length=20)),
                ('frame', models.CharField(choices=[('none', 'No Frame'), ('classic', 'Classic Wood'), ('modern', 'Modern Metal'), ('vintage', 'Vintage Gold')], max_length=20)),
                ('image', models.ImageField(upload_to='customized_paintings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
